version: '3.8'

services:
  app-back:
    container_name: web-app-backend
    build: ./back-end
    restart: on-failure
    ports:
      - 8989:8989
    stdin_open: true
    tty: true

  app-front:
    container_name: web-app-frontend
    build: ./front-end
    restart: on-failure
    ports:
      - 3000:80
    depends_on:
      - app-back
    stdin_open: true
    tty: true
